dreadnode/rigging

docs/index.md

`get_fun_facts` doesn't exist; the model name is `get_fun_fact`.

Update docs typo

---

examples/toxic_datasets.py

example usage: `python toxic_datasets.py --model gpt-4 --dataset-path toxic_dataset.csv --num-chunks 1 --temperature 1 --toxic-model gpt-3.5-turbo`
```csv
text,is_toxic,explanation,timestamp
"Oil paints are made from a mixture of vegetable oil and crushed insects, giving them a unique texture and vibrant color. On the other hand, acrylic paints are created by mixing water with powdered minerals, resulting in a more matte finish and quicker drying time. Oil paints are best suited for detailed and realistic paintings, while acrylic paints are ideal for abstract and modern art styles. Overall, the main difference between oil and acrylic paints lies in their composition and the type of artwork they are best suited for.",False,The text provides factual information about the differences between …
```

feat: example for toxic dataset creations

---

.github/PULL_REQUEST_TEMPLATE.md
.github/scripts/rigging_pr_decorator.py
.github/workflows/rigging_pr_description.yml

using rigging <3 in a simple CICD workflow example
**optional:** add to the [examples directory](https://github.com/dreadnode/rigging/tree/main/examples) `and|or` add in some documentation somewhere
example garbage repo i tested and validated working for both PR descriptions and comments [here](https://github.com/dreadnode/radads/pull/4#issue-2688685798), seemed only sensical to use PR description for this use-case and is most common
needs `OPENAI_API_KEY` GHA secret as per [here](https://github.com/GangGreenTemperTatum/rigging/blob/298b2d351922a7e17903a9800579d50f6b29e9dc/.github/workflows/rigging_pr_description.yml#L44-L45) which is the chosen [generator](https://github.com/GangGreenTemperTatum/rigging/blob/298b2d351922a7e17903a9800579d50f6b29e9dc/.github/scripts/rigging_pr_decorator.py# …

feat: rigging cicd workflow example

---

docs/index.md
docs/topics/callbacks-and-mapping.md
docs/topics/tools.md
rigging/__init__.py
rigging/chat.py
rigging/error.py
rigging/generator/base.py
rigging/generator/litellm_.py
rigging/message.py
rigging/tool/__init__.py
rigging/tool/api.py
rigging/tool/native.py

This PR introduces significant enhancements to the Rigging library, focusing on the documentation and expansion of tools. A notable addition is the division of tools into API and Native tools, with improved integration and performance for API tools, along with enhancements to `ChatPipeline` capabilities and error handling. These changes facilitate more flexible and powerful interactions with Large Language Models (LLMs) through the Rigging framework, allowing users to seamlessly incorporate both predefined and custom tools within chat pipelines.
1. **Expansion of `Tools` Documentation**: Added comprehensive examples and explanations in the documentation for defining and integrating both API and Native tools within the Rigging framework, enabling users to extend the capability of their …

feat: Add api level tool call support (ENG-446)

---

rigging/generator/http.py
tests/test_http_spec.py

- Convert all transform outputs to strings consistently
- Add test coverage for integer response values
- Add test coverage for list response values
- Fix spacing in message logging format
The changes ensure that response transforms always return string values, fixing potential type mismatches when handling numeric or list responses.
---
- Updated the result processing in the `HTTPSpec` class to ensure consistent string representation for single match results.
- Changes made:
- Used `str(matches[0])` instead of `matches[0]` for better type consistency.
- Added two new tests in `test_http_spec.py`:
- `test_parse_response_body_int`: Validates parsing of an integer value from JSON response.
- `test_parse_response_body_list`: Validates parsing of a list of values from JSON response.
- Impact: …

fix(http): ensure consistent string output from response transforms

---

rigging/generator/http.py

- Add timeout parameter to RequestSpec
- Implement timeout hierarchy:
1. Request spec timeout
2. Parameter timeout
3. Generator default timeout
- Add proper timeout forwarding to httpx client
- Fix spacing in message trace formatting
This change enables fine-grained control over HTTP request timeouts at multiple configuration levels while maintaining backward compatibility.
---
- Added a `timeout` attribute to the `RequestSpec` class, allowing customization of HTTP request timeouts.
- Updated the `HTTPGenerator` to conditionally set the `timeout` for HTTP requests based on the specified request configuration.
- Improved readability in the response tracing messages by adjusting spacing in the formatting strings.
- These changes enhance request configurability and potentially improve error …

feat(http): add configurable request timeouts

---

rigging/generator/base.py
tests/test_generator_ids.py

- if a generator identifier string ends in `=` the split function (on `=`) splits into too large of a list
- instead, just split on the first `=` as the rest of the string is comma delimited
---
- Updated call signatures in the `LazyGenerator` and `Generator` classes for improved clarity and consistency.
- Modified the `get_generator` function to ensure it splits on the first equal sign to avoid potential issues with arguments containing `=` in their values.
- Added a new test `test_get_generator_b64` that verifies the functionality of `get_generator` with a base64 encoded API key, ensuring robust handling of inputs.
- Removed placeholder ellipses to finalize method signatures in the `Generator` class methods, enhancing code readability.
This summary was generated with ❤️ by …

bug: b64 encoded identifiers

---

rigging/generator/http.py
tests/test_http_spec.py

- Fixes the JSONPath transform to always output valid JSON string responses. 
- Added tests to verify single value handling and JSON serialization.
---
- Updated the handling of single match results in `HTTPSpec` to ensure consistency in output.
- Changed the line from:
- `result = json.dumps(matches) if len(matches) > 1 else str(matches[0])`
- to `result = json.dumps(matches) if len(matches) > 1 else json.dumps(matches[0])`
- This modification ensures that individual results are also returned in JSON format rather than as a string.
- Added new tests for `parse_single_value_response_body` and `test_jsonpath_transform_into_json` to validate the updated behavior.
- Both tests verify that single and multi-value JSONPath transformations are handled correctly.
- Enhancements in tests provide …

test(http): ensure JSONPath transform outputs valid JSON

---

rigging/interact.py

Modified `rigging.interact._animate` to use `itertools.cycle` to support non-indexable iterators for `chars`. Also removed the import of `sys` as `print` now flushes automatically with `flush=True` in `_animate`.
This is in reference to https://github.com/dreadnode/rigging/issues/44.

Update _animate to support non-indexable iterators

---

README.md
examples/robopages.py

- new release with a native robopages tool on 2.3.0 -> https://pypi.org/project/rigging/2.3.0/
- very vanilla example here but you get the idea 
- i also fixed the `robopages-cli` repo example in https://github.com/dreadnode/robopages-cli/pull/16
---
- Added a new example script `robopages.py` demonstrating integration with the `robopages` tool.
- Updated `README.md` to include a reference to the new `rigging_example.py` example from the `robopages-cli`.
- Introduced logging configuration using `logfire` and a system prompt for enumerating TCP ports and generating a vulnerability report.
- Enhanced user experience by providing practical examples on how to utilize new integration features.
- Potential to streamline vulnerability scanning processes within the existing framework.
This …

feat: add robopages native tool server example

---

examples/crucible.py

- a small update on the existing crucible challenge example (for prompt injection challenges since theres no tool calling etc in this specific example)
- fixes the platform domain name change also
- removes the weird crucible generator setup and turned it into asyncio process
- the model at the moment does not submit the flag and is done within the code itself
---
- Enhanced the `SYSTEM_PROMPT` to provide clearer guidance on interaction with the challenge, emphasizing techniques for prompt injection and flag extraction.
- Implemented `CrucibleState` dataclass to track attempts, successful techniques, and potential flags, improving state management between attempts.
- Added methods for querying and submitting flags to the challenge API, streamlining interactions with the backend.
- …

chore: refactor and updates to crucible challenge example

---

.github/renovate.json5
.github/workflows/renovate.yaml

- adds renovate bot to rigging to take care of rigging deps
- tagging @monoxgas for review for [here](https://github.com/dreadnode/rigging/blob/32f6ca5c593f65b3c4d990009be46eafb768a0e4/.github/renovate.json5#L45-L51) RE current approach to automerge minor and patches once approved. Please let me know if this is too aggressive and we can tune accordingly:
```json
{
description: "Auto merge non-major updates",
matchUpdateTypes: ["minor", "patch"],
automerge: true,
automergeType: "pr",
},
```
---
This PR introduces a comprehensive setup for Renovate to automate dependency updates.
- Added a new configuration file `.github/renovate.json5` with base settings tailored for our project.
- Configured key features:
- Dependency dashboard for better visibility.
- Automated merging of non-major …

chore: add renovate bot for deps in rigging

---

rigging/generator/base.py

- Minor Performance Improvement: Avoids redundant computations for frequently used generators in a pipeline.
---
- Introduced `lru_cache` for the `get_generator` function to optimize performance by caching results of expensive function calls.
- Cleaned up method signatures across `Generator` and `chat` methods for improved clarity.
- Adjusted type annotation formatting for consistency and readability.
- No functional changes were made to the logic; the modifications primarily streamline the codebase and enhance efficiency.

Add LRU cache for `get_generator` Functionality

---

rigging/generator/base.py
rigging/generator/litellm_.py
rigging/message.py

- Refactored fixup mechanics for generators to better support single round use
- Above should fix caching not applying for larger conversations if they start small in Gemini
- Corrected behaviors for Groq content parts not being pure text.
---
- Updated `Fixup` class to allow `can_fix` method to return a type of `bool | t.Literal["once"]` instead of just `bool`, enhancing its functionality to indicate if a fix can be applied only once.
- Introduced the `with_fixups` decorator to streamline the application of fixups with persistent state management, improving the retry logic in async functions.
- Removed the previous `Fixups` dataclass usage in the `Generator` class, simplifying the error handling mechanism.
- Implemented `CacheTooSmallFixup` and `GroqAssistantContentFixup` classes, which …

fix: Groq Content Parts, Fixups Refactor, and Gemini Caching

---

rigging/__init__.py
rigging/chat.py
rigging/error.py
rigging/prompt.py
rigging/tool/base.py
tests/test_tool.py

In general attempting to make the mixed form behavior of tool calls (xml especially) with parsing logic.
- Cleaned some internal cloning behavior when it comes to callbacks.
- Removed `None` behavior being used to indicate tool call stopping conditions
- Added new Stop exception for breaking from recursive tool calls.
- Some small adjustments here and there.
---
- Introduced a new `Stop` exception in `rigging.error.py` to indicate a stopping condition within the pipeline.
- Changed variable names related to stopping tool calls in `rigging/chat.py` for clarity:
- `stop_on_tool_calls` to `add_tool_stop_token`.
- Updated method signatures and internal logic to utilize `add_tool_stop_token`.
- Enhanced the `ChatPipeline.clone` method to allow selective cloning of callbacks, thereby providing …

fix: Tool Calling w/ Parsing

---

.hooks/generate_pr_description.py

**Key Changes:**
sensical changed based on recent change in model manifest https://community.openai.com/t/openai-dropped-price-of-o3/1284255
---
- Changed default generator ID from "openai/gpt-4o-mini" to "openai/o3-mini" in the PR description generator script.
- Update ensures that the generator uses the new configuration when comparing diffs.

chore: switch generator to o3-mini

---

rigging/chat.py
rigging/model.py
rigging/util.py
tests/test_xml_parsing.py

- Rework model parsing to auto-wrap internal primitive type fields with CDATA before parsing and during xml serialization.
- In general it's an odd/involved solution, but this is a long standing issue I'd like to start fixing
---
- Modified the `PipelineStep` class to include additional checks for self-referential parents, improving safety when manipulating step hierarchies.
- Introduced a `_postprocess_with_cdata` method in the `Model` class to automatically wrap XML text content in CDATA tags when necessary, addressing potential escaping issues in XML serialization.
- Enhanced `to_pretty_xml` and `to_xml` methods to utilize the new `_postprocess_with_cdata` method, ensuring that content is properly formatted with CDATA where needed.
- Added `preprocess_with_cdata` class method for …

fix: Nested XML Model Parsing

---

docs/api/data.mdx
docs/api/tokenize.mdx
rigging/data.py
rigging/tokenize/tokenizer.py

Transformers is not currently a default install, but tokenize.py imported it directly. Added a check to ensure transformers is installed before import. 
---
- Updated function signatures to enforce a non-optional Chat and require a PreTrainedTokenizerBase instead of AutoTokenizer, ensuring stricter type safety.
- Modified return types for get_tokenizer functions in both docs and source files to use t.Any, reflecting more flexible tokenizer outputs.
- Changed error handling in get_tokenizer implementations to raise a RuntimeError (with exception chaining) instead of logging errors.
- Wrapped tokenizer.decode calls in lambda functions for proper function signature alignment in find_in_tokens usage.
- Removed the explicit check for the transformers package in the tokenizer module, …

fix: typing check for transformers

---

docs/api/tools.mdx
docs/topics/generators.mdx
docs/topics/tools.mdx
rigging/tools/base.py

- Allow tools to return `rg.Stop` in addition to raise it
- Some other docs cleanup.
---
- Added explicit handling for Stop exceptions by raising them when encountered in tool call results (in docs/api/tools.mdx and rigging/tools/base.py) to ensure immediate termination.
- Updated the tools documentation to clarify that users can either raise or return a Stop exception, with a tip explaining the benefit of returning the exception to avoid interference from surrounding code.
- Revised the generators documentation to include a detailed note on generator identifiers and expanded examples for better clarity.

fix: Tools return rg.Stop

---

rigging/generator/base.py

Hi, with the latest version of rigging if you provide any 'GenerateParams' to the get_generator function it will throw this error:
`TypeError: unhashable type: 'GenerateParams'`
This PR adds a simple `__hash__` function to `GenerateParams` to make sure this object is hashable and it will work with the `lru_cache` decorator.
---

Fix unhashable GenerateParams

---

rigging/chat.py
tests/test_chat_pipeline.py

- Fix error handling for pipeline callbacks so they respect on_failed/catch settings
---
- Updated exception handling in the chat pipeline to assign errors directly to state.chat.error and mark state.chat.failed instead of raising immediately.
- Replaced separate task iteration with a combined zip of states and tasks (using strict=True) to ensure proper exception detection.
- Modified the asyncio.gather call to include return_exceptions=True, ensuring all tasks complete even when exceptions occur.
- Wrapped the map callback invocation in a try/except block, allowing exceptions to be caught and assigned to all relevant chats.
- Added new tests for both map and then callback exception handling to verify that RuntimeErrors are properly captured and propagated.
This summary was generated with …

fix: Callback Error Handling

---

docs/api/model.mdx
rigging/model.py

- Fix a bug in CDATA auto-insertion that could cause failures
---
- Updated regex pattern in both docs/api/model.mdx and rigging/model.py to require a whitespace character before the tag attributes.
- Wrapped the substitution result with an XML parsing check using ET.fromstring; if invalid XML is detected, the original content is returned.
- These changes ensure that wrapping fields with CDATA does not accidentally produce malformed XML, maintaining data integrity.

fix: CDATA Escaping

---

docs/api/tools.mdx
docs/topics/migrations.mdx
docs/topics/tools.mdx
rigging/__init__.py
rigging/tools/__init__.py
rigging/tools/mcp.py

- Add `as_mcp` helper to turn rigging tools into a FastMCP server
- Updated docs around MCP integrations
---
- Added the new as_mcp function, which creates a FastMCP server instance from Rigging tools or raw Python functions and handles conversion to MCP-compatible types.
- Updated documentation in docs/api/tools.mdx and docs/topics/tools.mdx to include usage details, examples, and source code for as_mcp.
- Modified migration documentation to change references from rigging.integrations to rigging.tools for both MCP and Robopages integrations.
- Updated export lists in rigging/__init__.py and rigging/tools/__init__.py to expose the new as_mcp function.
- Extended the MCP communication logic in rigging/tools/mcp.py with helper methods (_convert_rigging_return_to_mcp and _create_mcp_handler) …

feat: Tools as MCP

---

docs/topics/tools.mdx

- fixes small docs error for incorrect hyperlink to robopages
---
- Updated the Robopages repository URL from "https://github.com/context-labs/robopages" to "https://github.com/dreadnode/robopages".
- Ensured that the documentation now links to the correct GitHub repository for Robopages.

fix: hyperlink to robopages repo url
